### ISSUE TITLE
Error: Invalid rich scalar: Field

### ISSUE THREAD

**Issue by coldstar1993** [o1-labs/o1js#1135]
My circuit dependency relationship is as: zkProgramC <-- zkProgramB <-- SmartContractA.  
I tried to trigger smartContractA with the proof from zkProgramB(zkProgramC), and get successful tx and broadcast at the first trigger.  However, when I trigger the second or more times, it throws an error as below:

```
Error: Invalid rich scalar: Field 10877295794357616459115299833550986754430745535593408272184814485138476140408
    at failwith (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:64877:50)
    at raise_invalid_scalar (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376100:36)
    at except (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376105:49)
    at /opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376146:61
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at /opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376117:64
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at map$14 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:78942:49)
    at caml_call2 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7702:28)
    at _hH4_ (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376387:58)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at _hHV_ (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376441:40)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at count_map (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:77630:21)
    at func$3 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:77656:33)
    at _hKK_ (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:375367:56)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at _hHV_ (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376441:40)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at creator (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:375280:36)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at /opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376511:46
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at _g$b_ (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:401043:43)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at /opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376572:60
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at of_json (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:375297:38)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at creator (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:375270:33)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at /opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376511:46
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at /opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:401833:47
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at /opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376572:60
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at of_json (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:375297:38)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at creator (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:375270:33)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at /opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376511:46
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at _g7C_ (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:403186:38)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at /opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376572:60
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at of_json (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:375297:38)
    at caml_call1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7700:28)
    at of_json (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:376649:31)
    at caml_call2 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7702:28)
    at account_update$1 (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:424307:56)
    at caml_call_gen (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:1987:17)
    at caml_call_gen (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:1990:16)
    at Object.accountUpdate (/opt/anomix_server/anomix-network/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:3581:16)
    at AccountUpdate.hash (file:///opt/anomix_server/anomix-network/node_modules/o1js/dist/node/lib/account_update.js:638:44)
    at AccountUpdate.toPublicInput (file:///opt/anomix_server/anomix-network/node_modules/o1js/dist/node/lib/account_update.js:642:34)
    at createZkappProof (file:///opt/anomix_server/anomix-network/node_modules/o1js/dist/node/lib/account_update.js:1318:37)
    at addProof (file:///opt/anomix_server/anomix-network/node_modules/o1js/dist/node/lib/account_update.js:1313:23)
    at addMissingProofs (file:///opt/anomix_server/anomix-network/node_modules/o1js/dist/node/lib/account_update.js:1285:52)
    at Object.prove (file:///opt/anomix_server/anomix-network/node_modules/o1js/dist/node/lib/mina.js:158:50)
    at file:///opt/anomix_server/anomix-network/apps/proof-generators/dist/src/provers/proof-worker-AnomixRollupContract.js:28:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async execCircuit (file:///opt/anomix_server/anomix-network/apps/proof-generators/dist/src/provers/proof-worker-AnomixRollupContract.js:42:21)
    at async process.<anonymous> (file:///opt/anomix_server/anomix-network/apps/proof-generators/dist/src/provers/proof-worker-AnomixRollupContract.js:14:17)
```

And then I reboot a new process again for repeated progress, it could always succeed at the first time, while all failed at second time.

So  I guess it's about the memory usage. Might be at the first time there is enough memory space, but from the second time, memory is not enough (perhaps it failed to release some memory? just guess.).

**Comment by mitschabaude** [comment]
It's weird, could you post the stack trace when running with
```
node --enable-source-maps
```

**Comment by mitschabaude** [comment]
It would possibly be easy to fix by switching to the TS version in `AccountUpdate.hash()`
