### ISSUE TITLE
Improve error message when using too many state fields. Example: `CircuitString`

### ISSUE THREAD

**Issue by emlautarom1** [o1-labs/o1js#1219]
I'm trying to set up a smart contract that takes a proof and uses it's public output to update a value in the contract's state. This is a minimal reproducible example:

```typescript
import { AccountUpdate, CircuitString, Experimental, Mina, PrivateKey, PublicKey, SmartContract, State, method, state } from "o1js";

const SomeProof = Experimental.ZkProgram({
  publicOutput: CircuitString,

  methods: {
    make: {
      privateInputs: [CircuitString],

      method(value: CircuitString): CircuitString {
        value.assertEquals(CircuitString.fromString('hello'));
        return value;
      },
    },
  },
});

class SomeProofClass extends Experimental.ZkProgram.Proof(SomeProof) { }

class SomeProofContract extends SmartContract {
  @state(CircuitString) value = State<CircuitString>();

  init() {
    super.init();
    this.value.set(CircuitString.fromString(''));
  }

  @method setValueFromProof(proof: SomeProofClass) {
    proof.verify();
    this.value.set(proof.publicOutput);
  }
}

describe('SomeProof', () => {
  let deployerAccount: PublicKey;
  let deployerKey: PrivateKey;
  let senderAccount: PublicKey;
  let senderKey: PrivateKey;
  let zkAppAddress: PublicKey;
  let zkAppPrivateKey: PrivateKey;
  let zkApp: SomeProofContract;

  beforeAll(async () => {
    await SomeProof.compile();
    await SomeProofContract.compile();
  });

  beforeEach(() => {
    const Local = Mina.LocalBlockchain({ proofsEnabled: true });
    Mina.setActiveInstance(Local);
    ({ privateKey: deployerKey, publicKey: deployerAccount } = Local.testAccounts[0]);
    ({ privateKey: senderKey, publicKey: senderAccount } = Local.testAccounts[1]);
    zkAppPrivateKey = PrivateKey.random();
    zkAppAddress = zkAppPrivateKey.toPublicKey();
    zkApp = new SomeProofContract(zkAppAddress);
  });

  async function localDeploy() {
    const txn = await Mina.transaction(deployerAccount, () => {
      AccountUpdate.fundNewAccount(deployerAccount);
      zkApp.deploy();
    });
    await txn.prove();
    await txn.sign([deployerKey, zkAppPrivateKey]).send();
  }

  it('generates and deploys the smart contract', async () => {
    await localDeploy();
    const value = zkApp.value.get();
    expect(value).toEqual(CircuitString.fromString(''));
  });

  it('correctly sets the value', async () => {
    await localDeploy();

    // Construct proof
    const hello = CircuitString.fromString('hello');
    const someProof = await SomeProof.make(hello);

    // Set value from proof
    const txn = await Mina.transaction(senderAccount, () => {
      zkApp.setValueFromProof(someProof);
    });
    await txn.prove();
    await txn.sign([senderKey]).send();

    const value = zkApp.value.get();
    expect(value).toEqual(hello);
  });
});
```

Trying to run this tests fails with the following exception:

```
  SomeProof
    ✕ generates and deploys the smart contract
    ✕ correctly sets the value

  ● SomeProof › generates and deploys the smart contract

    TypeError: Cannot set properties of undefined (setting 'isSome')

      at Function.setValue (o1js/src/lib/account_update.ts:897:22)
      at node_modules/o1js/src/lib/state.ts:199:23
          at Array.forEach (<anonymous>)
      at Object.set (o1js/src/lib/state.ts:198:21)
      at SomeProofContract.setValueFromProof (src/MinimalRepro.test.ts:30:16)
      at SomeProofContract.wrappedMethod (o1js/src/lib/zkapp.ts:199:31)
      at node_modules/o1js/src/lib/zkapp.ts:1195:68
      at node_modules/o1js/src/lib/proof_system.ts:583:12
      at node_modules/o1js/src/lib/provable-context.ts:94:16
      at mark_active (src/lib/snarky/src/base/snark0.ml:1167:19)
      at _o8x_ (src/lib/snarky/src/base/snark0.ml:1287:52)
      at as_stateful (src/lib/snarky/src/base/snark0.ml:755:15)
      at constraint_system (src/lib/snarky/src/base/runners.ml:263:7)
      at ../../../../../../workspace_root/src/lib/snarky/src/base/snark0.ml:1287:19
      at finalize_is_running (src/lib/snarky/src/base/snark0.ml:1272:15)
      at constraint_system (src/lib/snarky/src/base/snark0.ml:1286:7)
      at Object.constraintSystem (o1js/src/lib/provable-context.ts:93:45)
      at analyzeMethod (o1js/src/lib/proof_system.ts:578:19)
      at Function.analyzeMethods (o1js/src/lib/zkapp.ts:1190:49)
      at Function.compile (o1js/src/lib/zkapp.ts:678:10)
      at src/MinimalRepro.test.ts:45:29

  ● SomeProof › correctly sets the value

    TypeError: Cannot set properties of undefined (setting 'isSome')

      at Function.setValue (o1js/src/lib/account_update.ts:897:22)
      at node_modules/o1js/src/lib/state.ts:199:23
          at Array.forEach (<anonymous>)
      at Object.set (o1js/src/lib/state.ts:198:21)
      at SomeProofContract.setValueFromProof (src/MinimalRepro.test.ts:30:16)
      at SomeProofContract.wrappedMethod (o1js/src/lib/zkapp.ts:199:31)
      at node_modules/o1js/src/lib/zkapp.ts:1195:68
      at node_modules/o1js/src/lib/proof_system.ts:583:12
      at node_modules/o1js/src/lib/provable-context.ts:94:16
      at mark_active (src/lib/snarky/src/base/snark0.ml:1167:19)
      at _o8x_ (src/lib/snarky/src/base/snark0.ml:1287:52)
      at as_stateful (src/lib/snarky/src/base/snark0.ml:755:15)
      at constraint_system (src/lib/snarky/src/base/runners.ml:263:7)
      at ../../../../../../workspace_root/src/lib/snarky/src/base/snark0.ml:1287:19
      at finalize_is_running (src/lib/snarky/src/base/snark0.ml:1272:15)
      at constraint_system (src/lib/snarky/src/base/snark0.ml:1286:7)
      at Object.constraintSystem (o1js/src/lib/provable-context.ts:93:45)
      at analyzeMethod (o1js/src/lib/proof_system.ts:578:19)
      at Function.analyzeMethods (o1js/src/lib/zkapp.ts:1190:49)
      at Function.compile (o1js/src/lib/zkapp.ts:678:10)
      at src/MinimalRepro.test.ts:45:29
```

What I find curious is that if I replace all instances of `CircuitString` with `Bool`, `CircuitString.fromString('hello')` to `Bool(true)` and `CircuitString.fromString('')` to `Bool(false)`, then the contract works correctly. That is, the problem arises when I'm using `CircuitString` in the contract state.

According to the official docs, a `CircuitString` has a max length of 128 bytes and a `SmartContract` can store up to 256 bytes, so it's not a space issue.

**Comment by 45930** [comment]
@emlautarom1 sorry no one has responded to you, but a CircuitString is too long to fit in a smart contract.  It is 128 `Field`s and a contract can only hold 8 `Field`s.

**Comment by mitschabaude** [comment]
Urgh, the error message is awfully unhelpful. I'm changing the issue title to be about improving the error

**Comment by barriebyron** [comment]
We now have error message writing guidance https://github.com/o1-labs/docs2/wiki/zError-Messages

**Comment by mvkvc** [comment]
I ran into the same thing and it was unclear it was a storage issue, thankfully for this I was able to move forward.

**Comment by mitschabaude** [comment]
recently fixed
