### ISSUE TITLE
My smart contract tests do not pass no longer pass after update from SnarkyJS to o1js

### ISSUE THREAD

**Issue by marekyggdrasil** [o1-labs/o1js#1230]
I found my Smart Contract still fails its tests after updating from `SnarkyJS` to `o1js`. Unfortunately, unlike with https://github.com/o1-labs/o1js/issues/1218 this time I failed to isolate the error.

What I'm getting is

```
TypeError: Cannot read properties of undefined (reading 'x')
```

I could not isolate the error, but I did comment out as much as possible. Only one smart contract test runs and method that is being invoked has been entirely commented out (to ensure nothing in its body is causing the error) and I adjusted erguments to make it as similar as possible to Escrow smart contract deposit (which works and can be found here https://github.com/sqrt-xx/o1js-escrow-problem/blob/dfe3b7c946c7c90564f985c6d00b3ac1f4502baf/src/Escrow.ts#L10)

The trimmed code is here:

https://github.com/marekyggdrasil/mac/tree/90cc7c6e18a3b0d8b9fb3008e31530f0d0d55a7c/contracts

Way to reproduce:
1. Clone the repo
2. Checkout to commit `90cc7c6e18a3b0d8b9fb3008e31530f0d0d55a7c` (it is HEAD at the moment of writing this).
3. Go to smart contract directory `cd contracts`
4. Instal the dependencies `npm install`
5. Run the test `npm run test`

Expected behaviour: It should pass as it was passing with SnarkyJS `0.7.3`.
Actual behaviour: It fails with an error.

I did some research, similar errors occurr when `@prop` is missing in `CircuitValue` type but I can exclude that, not only it is not missing in my code but also I purposely removed `CircuitValue` type from the arguments of the `deposit` method.

**Comment by marekyggdrasil** [comment]
Of course, however I found typescript stack traces not so useful, they point to different places in the code than it actually occurs, maybe its an artifact of compiling ts to js? Anyway, here's the stack trace:
```
   ● Mac tests › should allow the withdrawal with no consequences to those who deposited after early cancellation

    TypeError: Cannot read properties of undefined (reading 'x')

      14 |   AccountUpdate,
      15 | } from 'o1js';
    > 16 |
         | ^
      17 | //import { Participant, Outcome, Preimage } from './preimage';
      18 | //import { makeDummyPreimage } from './dummy';
      19 | import { Outcome, Preimage } from './strpreim';

      at Function.toFields (node_modules/o1js/src/lib/circuit_value.ts:112:60)
      at node_modules/o1js/src/lib/zkapp.ts:517:13
          at Array.map (<anonymous>)
      at computeCallData (node_modules/o1js/src/lib/zkapp.ts:515:43)
      at Mac.wrappedMethod (node_modules/o1js/src/lib/zkapp.ts:206:34)
      at src/Mac.test.ts:16:23
      at createTransaction (node_modules/o1js/src/lib/mina.ts:237:11)
      at Object.transaction (node_modules/o1js/src/lib/mina.ts:596:14)
      at Module.transaction (node_modules/o1js/src/lib/mina.ts:1127:27)
      at deposit (src/Mac.test.ts:15:27)
      at Object.<anonymous> (src/Mac.test.ts:234:15)
```

**Comment by marekyggdrasil** [comment]
It was caused by the public key handling :) https://github.com/marekyggdrasil/mac/commit/596ef416f629c9bcd43462e0ff03eb8fedbe134d all good now! Thanks to DFST from Mina Discord!
