### ISSUE TITLE
`accountQuery` GraphQL query returns invalid permissions

### ISSUE THREAD

**Issue by MartinMinkov** [o1-labs/o1js#1424]
# Description

To reproduce this, start a local network using `lightnet` and specify o1js `0.16.0`.

When a call to [fetchAccount](https://github.com/o1-labs/o1js/blob/b5a131719203b8e19ec9bbbda041d5c05119e159/src/lib/fetch.ts#L152) is made, it returns an account where `permissions.setVerificationKey` is an empty object. This further breaks [this string serialization](https://github.com/o1-labs/o1js/blob/b5a131719203b8e19ec9bbbda041d5c05119e159/src/lib/account_update.ts#L382) and causes the following stacktrace:

```sh
/home/martin/Code/o1/Archive-Node-API/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/o1js_node.bc.cjs:6799
         throw err;
         ^

Error: Cannot parse invalid permission. [object Object] does not exist.
    at Object.fromString (file:///home/martin/Code/o1/Archive-Node-API/node_modules/o1js/dist/node/lib/account_update.js:174:23)
    at file:///home/martin/Code/o1/Archive-Node-API/node_modules/o1js/dist/node/lib/account_update.js:180:25
    at Array.map (<anonymous>)
    at Object.fromJSON (file:///home/martin/Code/o1/Archive-Node-API/node_modules/o1js/dist/node/lib/account_update.js:178:63)
    at parseFetchedAccount (file:///home/martin/Code/o1/Archive-Node-API/node_modules/o1js/dist/node/lib/mina/account.js:87:50)
    at fetchAccountInternal (file:///home/martin/Code/o1/Archive-Node-API/node_modules/o1js/dist/node/lib/fetch.js:112:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchAccount (file:///home/martin/Code/o1/Archive-Node-API/node_modules/o1js/dist/node/lib/fetch.js:90:12)
    at async fetchAccountInfo (file:///home/martin/Code/o1/Archive-Node-API/build/zkapp/utils.js:15:29)
    at async deployContract (file:///home/martin/Code/o1/Archive-Node-API/build/zkapp/utils.js:19:5)
    at async file:///home/martin/Code/o1/Archive-Node-API/build/tests/resolvers.test.js:78:9

Node.js v20.1.0
```

**GraphQL Query/Response**
```graphql
{
  account(publicKey: "B62qoDmPcovukEcFwAuRr5KV57eLcX2xw9CTsSZfYdTJJSAzQdgAbBo", token: "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf") {
    publicKey
    token
    nonce
    balance { total }
    tokenSymbol
    receiptChainHash
    timing {
      initialMinimumBalance
      cliffTime
      cliffAmount
      vestingPeriod
      vestingIncrement
    }
    permissions {
      editState
      access
      send
      receive
      setDelegate
      setPermissions
      setVerificationKey
      setZkappUri
      editActionState
      setTokenSymbol
      incrementNonce
      setVotingFor
      setTiming
    }
    delegateAccount { publicKey }
    votingFor
    zkappState
    verificationKey {
      verificationKey
      hash
    }
    actionState
    provedState
    zkappUri
  }
}
```
```json
{
  "publicKey": "B62qqGNimwE1ydLWohx9eo4neGmS7j2hi9zgRve9fBP9oC5CECwzDH7",
  "token": "wSHV2S4qX9jFsLjQo8r1BsMLH2ZRKsZx6EJd1sbozGPieEC4Jf",
  "nonce": "0",
  "balance": { "total": "1550000000000" },
  "tokenSymbol": "",
  "receiptChainHash": "2n1hGCgg3jCKQJzVBgfujGqyV6D9riKgq27zhXqYgTRVZM5kqfkm",
  "timing": {
    "initialMinimumBalance": null,
    "cliffTime": null,
    "cliffAmount": null,
    "vestingPeriod": null,
    "vestingIncrement": null
  },
  "permissions": {
    "editState": "Signature",
    "access": "None",
    "send": "Signature",
    "receive": "None",
    "setDelegate": "Signature",
    "setPermissions": "Signature",
    "setVerificationKey": {},
    "setZkappUri": "Signature",
    "editActionState": "Signature",
    "setTokenSymbol": "Signature",
    "incrementNonce": "Signature",
    "setVotingFor": "Signature",
    "setTiming": "Signature"
  },
  "delegateAccount": {
    "publicKey": "B62qqGNimwE1ydLWohx9eo4neGmS7j2hi9zgRve9fBP9oC5CECwzDH7"
  },
  "votingFor": "2mzWc7ZF8hRKvLyoLpKLZ3TSm8XSjfxZq67dphJpnjhYmU5Vja5Q",
  "zkappState": null,
  "verificationKey": null,
  "actionState": null,
  "provedState": null,
  "zkappUri": null
}

```

**Comment by MartinMinkov** [comment]
For some reason the compiled JS removes the `typeof` check inside the `fromJSON` call:

```js
fromJSON: (permissions) => {
        return Object.fromEntries(Object.entries(permissions).map(([k, v]) => [
            k,
            Permissions.fromString(v),
        ]));
    }
```

**Comment by MartinMinkov** [comment]
This was a case of stale npm dependencies :facepalm:
