### ISSUE TITLE
Packed.pack is weakly typed and will accept any input, even if wrong

### ISSUE THREAD

**Issue by dfstio** [o1-labs/o1js#1463]
The following code written in accordance with comments in https://github.com/o1-labs/o1js/blob/main/src/lib/provable-types/packed.ts#L33
```typescript
import { describe, expect, it } from "@jest/globals";
import { Field, Bool, Packed } from "o1js";

describe("Packed", () => {
  it("should pack the array of Bool", async () => {
    const unpacked: Bool[] = [Bool(true), Bool(false), Bool(true), Bool(false)];
    let PackedType = Packed.create(Bool);
    let packed = PackedType.pack(unpacked);
  });
});
```
gives error
```
 FAIL  tests/issues/packed.test.ts
  Packed
    ✕ should pack the array of Bool

  ● Packed › should pack the array of Bool

    TypeError: x.toField is not a function

      11 |     const unpacked: Bool[] = [Bool(true), Bool(false), Bool(true), Bool(false)];
      12 |     let PackedType = Packed.create(Bool);
    > 13 |     let packed = PackedType.pack(unpacked);
         |                             ^
      14 |   });
      15 | });
      16 |

      at Function.toInput (node_modules/o1js/dist/node/index.cjs:5010:26)
      at Function.pack (node_modules/o1js/dist/node/index.cjs:13233:22)
      at Object.<anonymous> (tests/issues/packed.test.ts:13:29)

```
when using o1js 0.16.2

**Comment by mitschabaude** [comment]
This code is not supposed to work. `Packed` can pack a single input which is of type `T`, not an array.

The bug here is that the code you show type-checks - because the static `pack()` method is too weakly types. Should add that method only in the `.create()` class factory

**Comment by dfstio** [comment]
Yes, `let packed = PackedType.pack(Bool(true));` works without error, although TypeScript shows that the argument should be of the type Bool[]:

![Screenshot 2024-02-27 at 18 42 36](https://github.com/o1-labs/o1js/assets/110384358/2b131d71-1b76-499a-9c4b-8183cd86994f)

How can I pack the array of Bool in this case to one Field? Is there a code example?

**Comment by mitschabaude** [comment]
Seems like you figures it out :D 

`Packed.pack` infers the type from the input, i.e. it has no opinion on what the type should be, and that's the problem 😅

**Comment by dfstio** [comment]
@mitschabaude, how is it possible to properly type the class that extends Struct? I would like to replace any with proper typing in the safe Struct serializing function.
```typescript
export function serializeStruct(params: { type: any; value: any }) {
  const { type, value } = params;
  if (type.name !== value.constructor.name) throw new Error("Type mismatch");
  if (type.name === undefined) throw new Error("Type name is undefined");
  return serializeFields([
    Encoding.stringToFields(type.name)[0],
    ...(type.toFields(value) as Field[]),
  ]);
}

export function deserializeStruct(params: {
  type: any;
  serializedStruct: string;
}) {
  const { type, serializedStruct } = params;
  const fields = deserializeFields(serializedStruct);
  if (fields[0].toBigInt() !== Encoding.stringToFields(type.name)[0].toBigInt())
    throw new Error("Type mismatch");
  return type.fromFields(fields.slice(1));
}

class MyStruct extends Struct({
  field1: Field,
  field2: Field,
  key: PublicKey,
}) {}

const str = serializeStruct({ type: MyStruct, value });
const value2 = deserializeStruct({
      type: MyStruct,
      serializedStruct: str,
    }) as MyStruct;
```

**Comment by mitschabaude** [comment]
@dfstio 
```ts
function serializeStruct<P extends Provable<any>>(params: { type: P; value: InferProvable<P> }): string;

function deserializeStruct<P extends Provable<any>>(params: { type: P; serializedStruct: string }): InferProvable<P>;
```

**Comment by dfstio** [comment]
Thank you, it works!
