### ISSUE TITLE
Broken `ZkProgram` Examples

### ISSUE THREAD

**Issue by harrysolovay** [o1-labs/o1js#1697]
# The following examples are broken

> (running with Node.js v21.7.3)

## https://github.com/o1-labs/o1js/blob/1588ee566d15a6e5ef6a1a611386c7da578ab48a/src/examples/zkprogram/program.ts

```
program digest Promise { <pending> }
compiling MyProgram...
/Users/harrysolovay/Desktop/mina-fungible-token/node_modules/o1js/src/lib/provable/core/provable-context.ts:105
    let finish = Snarky.run.enterConstraintSystem();
                        ^


TypeError: Cannot read properties of undefined (reading 'run')
    at Object.constraintSystem (o1js/src/lib/provable/core/provable-context.ts:105:25)
    at analyzeMethods (o1js/src/lib/proof-system/zkprogram.ts:483:45)
    at Object.compile (o1js/src/lib/proof-system/zkprogram.ts:508:23)
    at <anonymous> (/Users/harrysolovay/Desktop/mina-fungible-token/examples/proof-counting.eg.ts:33:27)
```

## https://github.com/o1-labs/o1js/blob/1588ee566d15a6e5ef6a1a611386c7da578ab48a/src/examples/zkprogram/program-with-input.ts

```
program digest Promise { <pending> }
compiling MyProgram...
/Users/harrysolovay/Desktop/mina-fungible-token/node_modules/o1js/src/lib/provable/core/provable-context.ts:105
    let finish = Snarky.run.enterConstraintSystem();
                        ^


TypeError: Cannot read properties of undefined (reading 'run')
    at Object.constraintSystem (o1js/src/lib/provable/core/provable-context.ts:105:25)
    at analyzeMethods (o1js/src/lib/proof-system/zkprogram.ts:483:45)
    at Object.compile (o1js/src/lib/proof-system/zkprogram.ts:508:23)
    at <anonymous> (/Users/harrysolovay/Desktop/mina-fungible-token/examples/proof-counting.eg.ts:33:27)
```

## https://github.com/o1-labs/o1js/blob/1588ee566d15a6e5ef6a1a611386c7da578ab48a/src/examples/zkprogram/dynamic-keys-merkletree.ts

```
Module '"o1js"' has no exported member 'FeatureFlags'.ts(2305)
```

**Comment by mitschabaude** [comment]
The first two are missing an `await` in front of `digest()`, and the third one should actually work on the `main` branch (where examples are expected to work) but uses a yet unreleased feature

**Comment by mitschabaude** [comment]
Solved
