### ISSUE TITLE
Unable to reconstruct PublicKey.empty() from events

### ISSUE THREAD

**Issue by asimaranov** [o1-labs/o1js#1786]
When event contains a struct with PublicKey.empty(), it's failed to reconstruct:
```
Events sync error Error: PublicKey: not a valid group element
    at /Users/andrey/projects/zknoid-backend/node_modules/.pnpm/o1js@1.4.0_patch_hash=4kniegfh6wxt6kgkrvn2yrltyu/node_modules/o1js/dist/node/index.cjs:8131:11
    at readBytes (/Users/andrey/projects/zknoid-backend/node_modules/.pnpm/o1js@1.4.0_patch_hash=4kniegfh6wxt6kgkrvn2yrltyu/node_modules/o1js/dist/node/index.cjs:4073:7)
    at Object.readBytes_ [as readBytes] (/Users/andrey/projects/zknoid-backend/node_modules/.pnpm/o1js@1.4.0_patch_hash=4kniegfh6wxt6kgkrvn2yrltyu/node_modules/o1js/dist/node/index.cjs:4033:24)
    at readBytes (/Users/andrey/projects/zknoid-backend/node_modules/.pnpm/o1js@1.4.0_patch_hash=4kniegfh6wxt6kgkrvn2yrltyu/node_modules/o1js/dist/node/index.cjs:4064:22)
    at readBytes_ (/Users/andrey/projects/zknoid-backend/node_modules/.pnpm/o1js@1.4.0_patch_hash=4kniegfh6wxt6kgkrvn2yrltyu/node_modules/o1js/dist/node/index.cjs:4033:24)
    at Object.fromBytes (/Users/andrey/projects/zknoid-backend/node_modules/.pnpm/o1js@1.4.0_patch_hash=4kniegfh6wxt6kgkrvn2yrltyu/node_modules/o1js/dist/node/index.cjs:4045:29)
    at Object.fromBase58 (/Users/andrey/projects/zknoid-backend/node_modules/.pnpm/o1js@1.4.0_patch_hash=4kniegfh6wxt6kgkrvn2yrltyu/node_modules/o1js/dist/node/index.cjs:8061:22)
    at Function.fromBase58 (/Users/andrey/projects/zknoid-backend/node_modules/.pnpm/o1js@1.4.0_patch_hash=4kniegfh6wxt6kgkrvn2yrltyu/node_modules/o1js/dist/node/index.cjs:15757:34)
    at Function.fromJSON (/Users/andrey/projects/zknoid-backend/node_modules/.pnpm/o1js@1.4.0_patch_hash=4kniegfh6wxt6kgkrvn2yrltyu/node_modules/o1js/dist/node/index.cjs:15790:23)
    ...
```

Error throws here:
![telegram-cloud-photo-size-2-5285105224102567840-y](https://github.com/user-attachments/assets/01b57f1b-4b0d-4993-8049-0cf55c075015)

I think it's an incorrect behavior, currently passing an empty publickey may block the contract.

Example, ticket `const ticket = Ticket.from([1, 1, 1, 1, 1, 1], PublicKey.empty(), 0);` passed to 
```ts
class BuyTicketEvent extends o1js.Struct({
    ticket: Ticket,
    round: o1js.Field,
}) {
}
```

**Comment by mitschabaude** [comment]
AFAICT this has nothing to do with events, it's just the `PublicKey.fromJSON()` method refusing to deserialize empty public keys.

> I think it's an incorrect behavior, currently passing an empty publickey may block the contract.

No, this can't block a contract, JSON serialization is not something you can or would do inside contract code. Also you could simply use a different method to reconstruct your event from the JSON.

Apart from that, JSON is not the format in which the protocol (graphql API) accepts and returns events.  They are transferred as raw list of field elements and reconstructed with `fromFields()` by o1js which doesn't throw this error.
