### ISSUE TITLE
sortMethodArguments ... privateInputs.length Cannot read properties of undefined (reading 'length') on TokenContractV2

### ISSUE THREAD

**Issue by Chomtana** [o1-labs/o1js#1789]
With this minimal code

```typescript
import { AccountUpdateForest, method, PublicKey, TokenContractV2, UInt64 } from 'o1js';

export class MinaToken extends TokenContractV2 {
  @method
  async approveBase(updates: AccountUpdateForest) {
    this.checkZeroBalanceChange(updates);
  }

}
```

Create a simple zkApp instance

```typescript
const zkAppPrivateKey = PrivateKey.random();
const zkAppPublicKey = zkAppPrivateKey.toPublicKey();
const zkApp = new MinaToken(zkAppPublicKey);
```

It's error

```
D:\projects\create-mina-token\contracts\node_modules\o1js\src\lib\proof-system\zkprogram.ts:812
  for (let i = 0; i < privateInputs.length; i++) {
                                    ^


TypeError: Cannot read properties of undefined (reading 'length')
    at sortMethodArguments (D:\projects\create-mina-token\contracts\node_modules\o1js\src\lib\proof-system\zkprogram.ts:812:37)
    at method (D:\projects\create-mina-token\contracts\node_modules\o1js\src\lib\mina\zkapp.ts:133:29)
    at __decorateClass (file:///D:/projects/create-mina-token/contracts/src/MinaToken.ts:1:374)
    at <anonymous> (d:\projects\create-mina-token\contracts\src\MinaToken.ts:5:9)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.10.0
```

**Comment by mitschabaude** [comment]
The code works in my environment.

What might happen for you is that the `@method` decorator doesn't work as expected in your environment. Check out the TS config of our project template, which among other things configures decorator support: https://github.com/o1-labs/zkapp-cli/blob/main/templates/project-ts/tsconfig.json

**Comment by Chomtana** [comment]
It seem to be due to the use of tsx

If build with tsc and run it works fine. Thanks
