### ISSUE TITLE
strange regression Expected an array for type, but got object

### ISSUE THREAD

**Issue by jmikedupont2** [o1-labs/o1js#1875]
I am working on automating tests and found this error, maybe you can help me diagnose it or you have seen it. 
I will try and repair it myself soon, but will skip it for now. 

https://github.com/jmikedupont2/o1js/actions/runs/11414056539/job/31762494200

```
Running test: ./dist/node/lib/provable/test/struct.unit-test.js
/workspace_root/src/bindings/ocaml/overrides.js:45
    if (err instanceof Error) throw err;
                              ^


Error: Expected an array for type, but got object
    at toFields (o1js/o1js/src/bindings/lib/provable-generic.ts:130:17)
    at Object.toFields (o1js/o1js/src/bindings/lib/provable-generic.ts:265:29)
    at Function.toFields (o1js/o1js/src/lib/provable/types/struct.ts:180:24)
    at <anonymous> (o1js/o1js/src/lib/provable/types/witness.ts:35:29)
    at exists (o1js/o1js/src/lib/provable/core/exists.ts:30:16)
    at Object.witness (o1js/o1js/src/lib/provable/types/witness.ts:32:14)
    at <anonymous> (o1js/o1js/src/lib/mina/zkapp.ts:315:35)
    at Array.map (<anonymous>)
    at MyContract.wrappedMethod (o1js/o1js/src/lib/mina/zkapp.ts:314:28)
    at <anonymous> (o1js/o1js/src/lib/provable/test/struct.unit-test.ts:248:18)

Node.js v18.20.4
Error: Process completed with exit code 7.```

**Comment by jmikedupont2** [comment]
After running again it did not happen, maybe some error condition that is not checked?

**Comment by jmikedupont2** [comment]
This is not reoccurring and it might just be out of date on my part
