### ISSUE TITLE
Deploy Error in 0.9.5

### ISSUE THREAD

**Issue by rpanic** [o1-labs/o1js#818]
In 0.9.5 calling deploy with `zkappKey` throws following error
```
This function can't be run outside of a checked computation.

      at failwith (../../../../home/gregor/.opam/4.14.0/lib/ocaml/stdlib.ml:29:34)
      at run (../../../../workspace_root/src/lib/snarky/src/base/snark0.ml:729:13)
      at exists (../../../../workspace_root/src/lib/snarky/src/base/snark0.ml:1203:11)
      at caml_call3 (node_modules/snarkyjs/dist/node/_node_bindings/snarky_js_node.bc.cjs:7611:28)
      at witness_minimal (../../../../workspace_root/src/lib/snarky_js_bindings/lib/snarky_js_bindings_lib.ml:1532:5)
      at caml_call_gen (../../../../builtin/+stdlib.js:32:12)
      at Function.<anonymous> (../../../../builtin/+jslib.js:252:14)
      at Function.Class.<computed> [as _witness] (node_modules/snarkyjs/src/snarky/proxy.js:20:52)
      at node_modules/snarkyjs/src/lib/circuit_value.ts:996:19
      at runWith (node_modules/snarkyjs/src/lib/global-context.ts:89:14)
      at Function.runWith (node_modules/snarkyjs/src/lib/global-context.ts:43:9)
      at Function.Circuit.witness (node_modules/snarkyjs/src/lib/circuit_value.ts:995:22)
      at memoizeWitness (node_modules/snarkyjs/src/lib/circuit_value.ts:1118:18)
      at Function.getSigningInfo (node_modules/snarkyjs/src/lib/account_update.ts:985:12)
      at AccountUpdate.sign (node_modules/snarkyjs/src/lib/account_update.ts:946:53)
      at Lender.deploy (node_modules/snarkyjs/src/lib/zkapp.ts:766:19)
      at Lender.deploy (src/lending/Lender.ts:82:15)
```

The same example works in 0.9.3

**Comment by MartinMinkov** [comment]
Can this be closed now? This is an old version, not sure if it's still present
